
package com.demo.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Empws", targetNamespace = "http://ws.demo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Empws {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveEmp", targetNamespace = "http://ws.demo.com/", className = "com.demo.ws.SaveEmp")
    @ResponseWrapper(localName = "saveEmpResponse", targetNamespace = "http://ws.demo.com/", className = "com.demo.ws.SaveEmpResponse")
    @Action(input = "http://ws.demo.com/Empws/saveEmpRequest", output = "http://ws.demo.com/Empws/saveEmpResponse")
    public String saveEmp(
        @WebParam(name = "arg0", targetNamespace = "")
        Emp arg0);

}
